spring:
  application:
    name: banking-transaction-microservices
  datasource:
    url: jdbc:mysql://localhost:3306/banking_transaction_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
      pathmatch:
        matching-strategy: ant-path-matcher
  kafka:
    bootstrap-servers:
      localhost:9092
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    
    hibernate:
      naming:
        physical-strategy: com.learning.utils.CustomNamingStrategy
      ddl-auto: update

server:
  port: 8100
  
eureka:
  client:
    enabled: false #if you don't want to run with eureka server
    register-with-eureka: true
    fetch-registery: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

#com:
#  learning:
#    jwtSecret: bankapp
#    jwtExpirationMs: 86400000


