spring:
  application:
    name: banking-customer-microservice
  datasource:
    url: jdbc:mysql://localhost:3306/banking_customer_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    
    hibernate:
      naming:
        physical-strategy: com.cogent.customer_service.utils.CustomNamingStrategy
      ddl-auto: update

server:
  port: 9001




